export const metadata = {
  title: 'Checkmate Analytics',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{margin: 0}}>{children}</body>
    </html>
  )
}
